name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    needs: ci-image-build-and-push
    runs-on: ubuntu-latest

    container:
      image: domwst/sex-ci-image
      options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Create cmake build directory
      run: mkdir cmake-build-test

    - name: Run cmake
      run: cd cmake-build-test && cmake -DSEX_DEVELOPER=ON ..

    - name: Run make
      run: cd cmake-build-test && make

    - name: Run tests
      run: cmake-build-test/tests/bin/sex_all_tests

