name: Development CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: domwst/sex-ci
      options: --privileged

    steps:
    - uses: actions/checkout@v3
    - name: Create cmake directory
      run: mkdir cmake-build-test
    - name: Run cmake
      run: cmake -DSEX_DEVELOPER=ON ..
