name: Development CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:.ci-container"
          push: false
          tags: sex-ci


  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: sex-ci
      options: --privileged

    steps:
    - uses: actions/checkout@v3
    - name: Create cmake directory
      run: mkdir cmake-build-test
    - name: Run cmake
      run: cd cmake-build-test && cmake -DSEX_DEVELOPER=ON ..
    - name: Run make
      run: cd cmake-build-test && make
    - name: Run tests
      run: cmake-build-test/tests/bin/sex_all_tests

